import { getRandomItems } from "./utils";

export function Html5Game({ gameName }: { gameName: string }) {
  return (
    <div className="h-full w-full bg-green-500">
      <iframe
        src={`https://funhtml5games.com?embed=${gameName}`}
        className="h-full w-full"
      />
    </div>
  );
}

const gamesList = [
  "minicraft",
  "bomberman",
  "wordle",
  "mazeblox",
  "coloringminecraft",
  "mariokart",
  "snake2",
  "minionkart",
  "angrybirds",
  "sonic",
  "mariofps",
  "sonicmario",
  "pacmanfps",
  "blockfall",
  "2048bit",
  "snake3d",
  "pixelminer",
  "captainreverso",
  "sokoban",
  "cargotruck",
  "flappytrump",
  "blockescape",
  "mazeballs",
  "neptuneblue",
  "helicoptergame",
  "angrymex",
  "booshsub",
  "alex4",
  "sokoban3d",
  "mariopacman3d",
  "roboflip",
  "springyninja",
  "buildingblocks",
  "popstar",
  "pokeninja",
  "mario",
  "minionescape",
  "zigzagzep",
  "pacmandash",
  "crazytaxi",
  "donkeykong",
  "rescuecopter",
  "rickdangerous",
  "retroracer",
  "mariojump",
  "pacman3d",
  "eastercoloring",
  "doodlejump",
  "gauntlet",
  "drunkdrive",
  "geomjump",
  "pipemania",
  "airstrike",
  "pokemoncrush",
  "spaceinvaders",
  "flappysanta",
  "timberman",
  "crushybird",
  "tetris",
  "pacman",
  "lemmingsxmas",
  "pandacatch",
  "pixelass",
  "gtacraft",
  "canabalt",
  "santajump",
  "santadash",
  "outrun",
  "fruitninja",
  "breakaway",
  "coil",
  "hydraulicpress",
  "cave",
  "angryturds",
  "drmario",
  "mcmaze",
  "timbercraft",
  "flappy",
  "breakoutminecraft",
  "roadblocks",
  "exolon",
  "manicminer",
  "escapepit",
  "sasquash",
  "geomdash",
  "marioeditor",
  "frogger",
  "jelly",
  "minimassacre",
  "bubblebobblehtml5",
  "lemmings",
  "tappyplanes",
  "blockninja",
  "racer10k",
  "mctetris",
];

export function getFourRandomGames() {
  return getRandomItems(gamesList, 4);
}
